name: Web-CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "22.4.0"

      - name: Install dependencies
        run: npm install

      - name: Build app bundle
        run: npm run build:prod

      # - name: Change name index for home
      #   run: mv dist/anypackweb/browser/index.html dist/anypackweb/browser/404.html

      #deploy to git
      - name: Deploy to pages
        uses: crazy-max/ghaction-github-pages@c05ee637ec73429400a359430db8e5629f3f2564
        with:
          build_dir: dist/anypackweb/browser
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
