name: Web-CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "22.4.0"

      - name: Install dependencies
        run: npm install

      - name: Build app bundle
        run: npm run build:prod

      - name: Copy index.html to 404.html
        run: cp dist/anypackweb/index.html dist/anypackweb/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/anypackweb
